bundler_args: --without development:production

rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head

env: PADRINO_ENV=test

script: bundle exec padrino rake dm:auto:migrate spec

notifications:
  irc: "irc.freenode.org#pivotter"
